apiVersion: v1
kind: Service
metadata:
 name: web-nginx
spec:
 type: NodePort
 ports:
  - name: web01
    port: 80
    nodePort: 31234
  - name: web02
    port: 81
    nodePort: 31235
 selector:
   app: web-nginx

