apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grafana.fullname" . }}-secret
  labels: {{ include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.admin.password }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.admin.password | b64enc | quote }}
  {{- else }}
  GF_SECURITY_ADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if and .Values.smtp.enabled (not .Values.smtp.existingSecret) }}
  {{- if and .Values.smtp.user .Values.smtp.password }}
  GF_SMTP_USER: {{ .Values.smtp.user | b64enc | quote }}
  GF_SMTP_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}
  {{- end }}
  {{- end }}
