apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-yum
  labels:
    name: nginx-yum
spec:
  replicas: 1
  selector:
    name: nginx-yum
  template:
    metadata:
      labels:
       name: nginx-yum
       app: nginx-yum
    spec:
      containers:
      - name: nginx-yum
        image: docker.io/nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/
            name: nginx-data
      volumes:
       - name: nginx-data
         hostPath:
          path: /data/nginx
      # nodeSelector:
      #  disktype: master
