apiVersion: v1
kind: Service
metadata:
  name: nginx-yum
  labels:
   name: nginx-yum
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
    nodePort: 42346
  selector:
    name: nginx-yum